name: Waystones
version: 1.0
author: Emreeocn
main: at.emreeocn.waystone.WaystonePlugin
api-version: 1.19
commands:
  waystone:
    description: Waystone command
    usage: /<command> [args]
    aliases: [ws]
    permission: waystone.command
    permission-message: You don't have permission to use this command.